<a href="https://colab.research.google.com/github/MartaKwinto/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy
https://numpy.org/

# Podstawy

In [3]:
import numpy as np
help(np.array)

1D Array

In [19]:
x = np.array([1, 3]) #tablica jednowymiarowa
x

array([1, 3])

In [ ]:
print(x) #wyprintowanie tablicy

In [20]:
type(x) #funkcja type sprawdza typ obiektu x

numpy.ndarray

In [21]:
x.ndim #wymiar tablicy (w skrócie - ilość zagnieżdżonych list)

1

In [22]:
x.shape #kształt tablicy -> w postaci tupla (normalnie (l.wierszy, l.kolumn), gdy jest 1 wiersz to wtedy (l.kolumn,))

(2,)

In [23]:
x.size #liczba elementów tablicy

2

In [24]:
x.dtype #rodzaj danych

dtype('int64')

In [25]:
x = np.array([1.3, 2.3, 1.4]) #tablica 1wymiarowa, dane typu float
x

array([1.3, 2.3, 1.4])

In [26]:
x.dtype #typ danych - float

dtype('float64')

2D Array

In [27]:
x = np.array([[1, 2], [-3, 1]]) #tablica 2wymiarowa
x

array([[ 1,  2],
       [-3,  1]])

In [28]:
x.ndim #wymiar tablicy

2

In [29]:
x.shape #kształt tablicy

(2, 2)

In [30]:
x.size #liczba elementów w tablicy

4