<a href="https://colab.research.google.com/github/MartaKwinto/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy
https://numpy.org/

# Podstawy

In [3]:
import numpy as np
help(np.array)

1D Array

In [19]:
x = np.array([1, 3]) #tablica jednowymiarowa
x

array([1, 3])

In [ ]:
print(x) #wyprintowanie tablicy

In [20]:
type(x) #funkcja type sprawdza typ obiektu x

numpy.ndarray

In [21]:
x.ndim #wymiar tablicy (w skrócie - ilość zagnieżdżonych list)

1

In [22]:
x.shape #kształt tablicy -> w postaci tupla: (l. tablic, l.wierszy, l.kolumn),
#gdy jest 1wym. tablica to jest to tylko l.kolumn, gdy 2wym. to l.wierszy, l.kolumn, a gdy 3wym. to l.tablic, l.wierszy, l.kolumn

(2,)

In [23]:
x.size #liczba elementów tablicy

2

In [24]:
x.dtype #rodzaj danych

dtype('int64')

In [25]:
x = np.array([1.3, 2.3, 1.4]) #tablica 1wymiarowa, dane typu float
x

array([1.3, 2.3, 1.4])

In [26]:
x.dtype #typ danych - float

dtype('float64')

2D Array

In [31]:
x = np.array([[1, 2, 4], [-3, 1, 6]]) #tablica 2wymiarowa
x

array([[ 1,  2,  4],
       [-3,  1,  6]])

In [32]:
x.ndim #wymiar tablicy

2

In [34]:
x.shape #kształt tablicy (2 wiersze, 3 kolumny)

(2, 3)

In [35]:
x.size #liczba elementów w tablicy

6

3D Array

In [40]:
x = np.array([
    
    [[4, 3, 1],
      [3, 6, 7]],

    [[4, 5, 7],
     [3, 4, 6]],
     
     [[3, 5, 6],
      [5, 6, 7]]
])
x

array([[[4, 3, 1],
        [3, 6, 7]],

       [[4, 5, 7],
        [3, 4, 6]],

       [[3, 5, 6],
        [5, 6, 7]]])

In [41]:
x.ndim

3

In [42]:
x.shape

(3, 2, 3)

Typy danych